// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// selectCrosses
Rcpp::List selectCrosses(arma::uword nCross, double targetAngle, arma::vec& u, arma::mat& G, double probMut, arma::uword nMutate, arma::uword nSel, arma::uword nPop, arma::uword maxGen, arma::uword maxRun, double anglePenalty, int nThreads);
RcppExport SEXP _cgiarOcs_selectCrosses(SEXP nCrossSEXP, SEXP targetAngleSEXP, SEXP uSEXP, SEXP GSEXP, SEXP probMutSEXP, SEXP nMutateSEXP, SEXP nSelSEXP, SEXP nPopSEXP, SEXP maxGenSEXP, SEXP maxRunSEXP, SEXP anglePenaltySEXP, SEXP nThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uword >::type nCross(nCrossSEXP);
    Rcpp::traits::input_parameter< double >::type targetAngle(targetAngleSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type u(uSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< double >::type probMut(probMutSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type nMutate(nMutateSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type nSel(nSelSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type nPop(nPopSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type maxGen(maxGenSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type maxRun(maxRunSEXP);
    Rcpp::traits::input_parameter< double >::type anglePenalty(anglePenaltySEXP);
    Rcpp::traits::input_parameter< int >::type nThreads(nThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(selectCrosses(nCross, targetAngle, u, G, probMut, nMutate, nSel, nPop, maxGen, maxRun, anglePenalty, nThreads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cgiarOcs_selectCrosses", (DL_FUNC) &_cgiarOcs_selectCrosses, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_cgiarOcs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
