# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

selectCrosses <- function(nCross, targetAngle, u, G, probMut = 0.01, nMutate = 2L, nSel = 500L, nPop = 10000L, maxGen = 1000L, maxRun = 100L, anglePenalty = 0.5, nThreads = 4L) {
    .Call(`_cgiarOcs_selectCrosses`, nCross, targetAngle, u, G, probMut, nMutate, nSel, nPop, maxGen, maxRun, anglePenalty, nThreads)
}

